*sysfunc  Friday, June 7, 2002 - SALES REPORT.;
title "%sysfunc(today(),weekdate.) - SALES REPORT";
title "Report Produced on 
              %sysfunc(left(%qsysfunc(today(),worddate.)))";
%let current=%sysfunc(time(),time.);
*&lib need two dot;
proc &graphics.chart data=&lib..y&year&month;

*symput in data step;
options symbolgen pagesize=30;
%let crsnum=3;
data revenue;
   set sasuser.all end=final;
   where course_number=&crsnum;
   total+1;
   if paid='Y' then paidup+1;
   if final then do;
      if paidup<total then do;
         call symput('foot','Some Fees Are Unpaid');
      end;
      else do;
         call symput('foot','All Students Have Paid');
      end;
   end;
run;
*unify format strip title;
%let crsnum=3;
data revenue;
   set sasuser.all end=final;
   where course_number=&crsnum;
   total+1;
   if paid='Y' then paidup+1;
   if final then do;
      call symput('numpaid',trim(left(paidup)));
      call symput('numstu',trim(left(total)));
      call symput('crsname',trim(course_title));
      call symput('date',put(begin_date,mmddyy10.));
      call symput('due',
          trim(left(put(fee*(total-paidup),dollar8.))));
   end;
run;
*assign multi macro variable;
data _null_;
   set sasuser.courses;
   call symput(course_code, trim(course_title));
run;
%put _user_;
*rescan rule;
%let crsid=C002;
proc print data=sasuser.schedule noobs label;
   where course_code="&crsid";
   var location begin_date teacher;
   title1 "Schedule for &&&crsid";
run;