 *create data sample;
 do pickit=1 to 142 by 10;
        set sasuser.sale2000 point=pickit;
        output;
     end;
 *inf loop;
 data sasuser.subset;
    do pickit=1 to 142 by 15;
       set sasuser.revenue point=pickit;
       output;
    end;
    stop;
 run;
 *unknown number;
 data sasuser.subset;
    do pickit=1 to totobs by 10;
       set sasuser.revenue point=pickit nobs=totobs;
       output;
    end;
    stop;
 run;
 *generate random number;
 data random2;
    do i=1 to 10 by 1;
       varone=ranuni(10);
       output;
    end;
 run;
 *1-50;
ceil(ranuni(0)*50);
*empid unique;
 data simple2 (index=(division empid/unique));
    set sasuser.empdata;
 run;
 *comp index;
  data composite (index=(Empdiv=(division empid)));
    set sasuser.empdata;
 run;
 OPTIONS MSGLEVEL= N | I;
 *use dataset create index;
 proc datasets library=sasuser nolist;
    modify sale2000;
    index delete origin;
    index create flightid;
    index create Fromto=(origin dest);
 quit;